version: '3'

services:

  # [Comment to turn off]:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

  # [Comment to turn off]:
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  # [Comment to turn off]:
  server3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"

  # Proxy-pass [Comment to turn off]:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
